name: Markdown Quality Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  markdown-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: AutoCorrect
        uses: huacnlee/autocorrect-action@main

      - name: Markdown Lint
        uses: DavidAnson/markdownlint-cli2-action@v20
        with:
          globs: |
            README.md
      
      - name: Markdown Link Check
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'
          use-verbose-mode: 'no'
          folder-path: '.'
